#:schema node_modules/wrangler/config-schema.json
name = "pinnacle-inn-website"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[vars]
NEXT_TELEMETRY_DISABLED = "1"
